resolver: lts-13.0

packages:
- .
- location:
    git: https://github.com/konn/haskell-src-exts-qq.git
    commit: 12ac97a284d35cfb65b2c5ccfaf6a411f7dadbec
  extra-dep: true

extra-deps:
- ../../too-fast-too-free
- haskell-src-exts-simple-1.20.0.0@sha256:fff5fe1efbca954ba531e9981b5677226eaecc7515788fb77289c4127fb7350d

